parameters:
    openai_api_key: '%env(OPENAI_API_KEY)%'
    allowed_users: '%env(ALLOWED_USERS)%'
    mail_from: '%env(default:default_mail_from:MAIL_FROM)%'
    default_mail_from: 'noreply@dopaminder.app'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\BrainDumpAnalyzer:
        arguments:
            $openAiApiKey: '%openai_api_key%'

    App\Service\PlanningScheduleGenerator:
        arguments:
            $openAiApiKey: '%openai_api_key%'

    App\Service\UserService:
        arguments:
            $allowedUsers: '%allowed_users%'

    App\Service\AuthMailerService:
        arguments:
            $mailFrom: '%mail_from%'
